compile_pdf:
  stage: build
  image: texlive/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  tags:
    - ci-runner
  script: 
        - make clean
        - make pdf
  artifacts:
    paths: 
      - ./outputs/main.pdf  # instruct GitLab to keep the main.pdf file
    expire_in: 1 year

compile_greyscale:
  stage: build
  image: texlive/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  tags:
    - ci-runner
  script: 
        - make clean
        - make greyscale
  artifacts:
    paths: 
      - ./outputs/main_grey.pdf  # instruct GitLab to keep the main_grey.pdf file
    expire_in: 1 year

compile_noappendix:
  stage: build
  image: texlive/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  tags:
    - ci-runner
  script: 
        - make clean
        - make no-appendix
  artifacts:
    paths: 
      - ./outputs/main_no-appendix.pdf  # instruct GitLab to keep the main_no-appendix.pdf file
    expire_in: 1 year

compile_noacknowledgements:
  stage: build
  image: texlive/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  tags:
    - ci-runner
  script: 
        - make clean
        - make no-acknowledgements
  artifacts:
    paths: 
      - ./outputs/main_no-acknowledgements.pdf  # instruct GitLab to keep the main_no-acknowledgements.pdf file
    expire_in: 1 year

