#!/bin/bash
# Run docker, including `sudo` if necessary
# - After using `sudo`, files generated by docker are owned by root. To fix
#   this, change the owner of all recent root-owned files to $USER.
#
# USAGE: ./docker.sh DOCKER-ARGUMENTS

# checking if running docker needs sudo
# on ubuntu, sudo is typically required to use docker commands
# on mac os, sudo is typically not required
if docker version 2>&1 | grep "permission" >/dev/null ; then
	# need sudo
	sudo docker "$@"
	# find files owned by root 
	find . -group root -cmin -5 | xargs --no-run-if-empty sudo chown -R $USER:$USER
else
	# does not need sudo
	docker "$@"
fi
