name: Build LaTeX paper
permissions: write-all 
on: 
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            apk add --no-cache python3 py3-pip
            make all 
            make abstract
      - name: Delete placeholder release
        uses: actions/github-script@v7
        continue-on-error: true # in case there's no existing release
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo } = context.repo
            const { data: { id } } = await github.rest.repos.getLatestRelease({ owner, repo })
            await github.rest.repos.deleteRelease({ owner, repo, release_id: id })
      - name: Delete release tag
        run: |
          git tag -d release
          git push origin :release
        continue-on-error: true # in case there's no existing release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          body: "Placeholder release for the latest build "
          name: Latest
          tag_name: release
          files: |
            outputs/main.pdf
            outputs/main_grey.pdf
            outputs/main_no-appendix.pdf
            outputs/main_no-acknowledgements.pdf
            outputs/abstract.txt

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
